### ISSUE TITLE
[bug: Solved] cannot interact in discussions. Http request filed status 400

### ISSUE THREAD

**Issue by RajatM24** [axiel7/AniHyou-android#169]
**Describe the bug (required)**
Whenever I try to publish any comment it simple return the following error
HTTP request failed with status code '400'

**To Reproduce**
1. Go to any anime's threads section '
2. Click on 'any thread and try to make a comment then click on publish button'

**Expected behavior**
I expect the app to properly submit the comment when clicked Publish

**Enviroment (required)**
 - Device model: Samsung F34 5g
 - Android version: 14
 - App version: 1.3.3

**Comment by RajatM24** [comment]
Possibly related but i can neither like the threads

**Comment by axiel7** [comment]
Known bug. Fixed in latest beta 1.3.4

**Comment by RajatM24** [comment]
Ok so roughly how long till it makes its way to fdroid

**Comment by axiel7** [comment]
I'll probably release a new stable version by the end of this month

**Comment by SoiledBrush** [comment]
Still occuring on 1.3.4 on any page  ![Screenshot_20240730-193232.png](https://github.com/user-attachments/assets/657396c1-5506-4557-b3b4-a777b0b567ed)

**Comment by axiel7** [comment]
@SoiledBrush this is unrelated to this bug. AniList servers were down but it should work fine by now
